//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string AccountIBAN { get; set; }
        public int OwnerId { get; set; }
        public decimal Balance { get; set; }
        public int BonusPoints { get; set; }
        public string AccountType { get; set; }
        public bool IsClosed { get; set; }
    
        public virtual AccountType AccountType1 { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
